### ISSUE TITLE
How To Stop Simulation?

### ISSUE THREAD

**Issue by usmanumar2010** [aws-solutions/iot-device-simulator#13]
I am seeing on pressing a stop button simulation went into "stoping" mode ,which mean it does not stop until its duration completes. How can i stop simulation from the simulated ECS Engine ?

**Comment by vMarkGould** [comment]
I think my question might be similar to this one.

I am trying to find the best way to shut down the simulator so that it is no longer using any Elastic Container services. 

I don't want to have to remove the whole application and lose my configuration but rather shut down the application, while I am not using it so that I don't incur costs. Then be able to start up the application again, to run more simulations.

Any help much appreciated.

Thanks
Mark

**Comment by gsingh04** [comment]
@vMarkGould thanks for your feedback. I believe I understand your use-case, but just to be sure can you please answer following questions:
1. what steps can we take to reproduce this?
2. what is the observed behavior and how can we see the same?
3. what is the desired behavior?

**Comment by usmanumar2010** [comment]
@gsingh04 .Can you tell me what is the reverse mechanism happening to stop a simulator ?
For example: when press start SQS Queue send message and Simulated Engine listen that message to start(Ref : https://github.com/awslabs/iot-device-simulator/blob/master/source/simulator/lib/modules/device.js )

What happens in case of stop . Status toggle from "hydrated " to "sleeping" in dynamo.Is there other  procedure happening like dequeue and stop service at that specific device ID.If not then this severe bug!

**Comment by vMarkGould** [comment]
> @vMarkGould thanks for your feedback. I believe I understand your use-case, but just to be sure can you please answer following questions:
> 
> 1. what steps can we take to reproduce this?
I’m not really sure I have steps to reproduce. Rather I have used the cloud formation template to stand up the IoT device simulator, and can successfully use it. But now I would like to pause the use of the application so I don’t invite the change for running the simulator all the time especially the elastic container tasks. Essentially shutting down the app, but leaving all of the configuration there so that I can restart it when I need to.

> 2. what is the observed behavior and how can we see the same?
I can not find a way to shutdown the simulator, I tried stopping the container tasks manually but they automatically restart.


> 3. what is the desired behavior?

To be able to completely shutdown the application simulator without deleting it. And be able to start the simulator application again maintaining the configuration for device types and widgets.

Hope this helps.

**Comment by vMarkGould** [comment]
Hi @gsingh04 did you have a response to the above?

Do you need any other information?

regards

Mark

**Comment by gsingh04** [comment]
Thanks for reporting this behavior and confirming my understanding. We have added this behavior to be fixed in next iteration of the solution. We are currently scoping the next release. Please continue to monitor the repo for updates.

**Comment by G-Lenz** [comment]
The solutions has undergone a complete refresh in v3.0.0. The solution sets the stage to "stopping" until it can next check for the stage of the running simulation. It checks the stage in Amazon DynamoDB every 30 seconds. If the stage is "stopping" when it next checks, it will end the simulation and set the stage to "stopped".
