### ISSUE TITLE
Resetting password does not work with email address.

### ISSUE THREAD

**Issue by ms-schneider-electric** [aws-solutions/iot-device-simulator#2]
Upon the first login to the simulator console (Sim.Console) you are requested to change you password.

On the change your password page it asks for your email.  However, you are returned a user not found exception when you enter in your email/old pw/new pw.

I was able to get this page to work by entering in the user name of the identity (not the email), which just the email with dots replaced by underscores.  This was a total random try to get this to work, and it worked...

But the page should be fixed to work the email (since that is what it is asking for).

**Comment by shsenior** [comment]
Hi @ms-schneider-electric - Can you provide some more details? What browser are you using and os?

**Comment by ms-schneider-electric** [comment]
I am using
- Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- Windows 10 Pro v1709

**Comment by muhufuk** [comment]
@shsenior why did you close this issue ? problem is still persist.

**Comment by shsenior** [comment]
We will take another look at the reported issue. In the meantime, you can use your username. 

Is your issue the same as above or when you are reseting your password after you have successfully logged into the console?

**Comment by muhufuk** [comment]
I have also faced ms-schneider-electric's problem.

"On the change your password page it asks for your email. However, you are returned a user not found exception when you enter in your email/old pw/new pw."

I have spent some time in order to change my pw finally I have found this issue and solved my problem with ms-schneider-electric'comment ("I was able to get this page to work by entering in the user name of the identity (not the email), which just the email with dots replaced by underscores. This was a total random try to get this to work, and it worked..")

**Comment by arktyle** [comment]
I have the same problem, when my mail has a dot.
But if my email has no characters, I connect without problems.

**Comment by byongwu** [comment]
Hi. I also got it worked around by inserting `user ID` instead of `user email`.
I searched and found this relevant code.
https://github.com/awslabs/iot-device-simulator/blob/master/source/console/src/app/public/auth/newpassword/newpassword.html#L45
However, I couldn't simply raise a PR via changing the text to `user ID` because then it will create incoherency with `[(ngModel)]="registrationUser.email"` data field. Please fix soon. This issue is becoming the first slap in the face for the "Let's give it a try" users.

**Comment by byongwu** [comment]
I raised the PR for the first users since user experience is the most important part.
@shsenior , please consider and fix the internal code as well. Thanks.

**Comment by G-Lenz** [comment]
The solution has undergone a complete refresh in the newest version, version 3.0.0. Resetting a password now functions properly as does the login and first time password change. We have removed the need for underscores and the login now functions properly with email.
